name: Python Static Check with BasedPyright and Ruff

on:
  push:
    paths:
      - '**.py'
      - '**.pyi'
      - '.github/workflows/python-staticcheck.yml'

jobs:
  type-check:
    strategy:
      matrix:
        version: ['3.9', '3.10', '3.11', '3.12', '3.13', '3.14']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install basedpyright

    - name: Install project
      run: |
        pip install -e .

    - name: Run basedpyright
      run: |
        basedpyright --pythonversion ${{ matrix.version }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      # Update output format to enable automatic inline annotations.
      - name: Run Ruff
        run: ruff check --output-format=github .
